"""add transaction table

Revision ID: 780387e47c0d
Revises: f855182ae79c
Create Date: 2023-04-29 10:08:39.810802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780387e47c0d'
down_revision = 'f855182ae79c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('share_price', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name=op.f('fk_transactions_stock_id_stocks')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('owned_stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_cost', sa.Integer(), nullable=True))
        batch_op.drop_column('purchase_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owned_stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_price', sa.INTEGER(), nullable=True))
        batch_op.drop_column('total_cost')

    op.drop_table('transactions')
    # ### end Alembic commands ###
