"""add share_price to transactions table

Revision ID: ada11bb39a14
Revises: f4422cc3c48d
Create Date: 2023-05-01 16:52:14.804096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ada11bb39a14'
down_revision = 'f4422cc3c48d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('share_price')

    # ### end Alembic commands ###
